version: '2'
services:
  front:
    image: nginx:1.12-alpine
    volumes:
     - ./front/dist:/usr/share/nginx/html
    ports:
     - "80:80"
    links:
     - api
  api:
    image: node:8.9
    command: node api/index.js
    working_dir: /usr/src/api
    volumes:
     - .:/usr/src/api
    ports:
     - "3000:3000"
    links:
     - db
  db:
    image: mongo:3.6
    ports:
     - "27017:27017"
