import React from 'react';

export default class Footer extends React.Component {
    render() {
        return (
            <footer className="footer">
                <div className="container">
                    <div className="content has-text-centered">
                        <p>
                            <strong>Cookies Store</strong> by <a href="https://snipcart.com">Snipcart</a> folks. This is a demo of a static site generated by Middleman.
                            Thanks to <a href="http://bulma.io">Bulma</a> for the simple CSS framework.
                        </p>
                        <p>
                            <a className="icon" href="https://github.com/snipcart/snipcart-middleman-integration">
                                <i className="fa fa-github"></i>
                            </a>
                        </p>
                    </div>
                </div>
            </footer>
        );
    }
}
